use_frameworks!

platform :ios, '9.0'

target 'CPPersonInfoCatogeryKit_Example' do
  pod 'CPPersonInfoCatogeryKit', :path => '../'

  target 'CPPersonInfoCatogeryKit_Tests' do
    inherit! :search_paths

    
  end
end
